### ISSUE TITLE
When wasted spark is active, sequencing randomly breaks

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/Arduino-Coil-On-Plug#2]
Due to interference caused by the spark going off, garbage pulses will sometimes trigger interrupt pins. There is already a check inside the interrupt to see if it was a real pulse or a garbage one, which works perfectly well when using fully sequential ignition.

The problem however is when wasted spark is taken into use. Then the amount of garbage on the inputs gets so high that it eventually counts it as a valid pulse. This increments the counter by one, and the engine abruptly stops.

Figure out some way to better filter the pulses, or make changes to the hardware

**Comment by rektbink** [comment]
I don't think you ever provided us code for the wasted spark setup? Or am I missing something?

**Comment by dalathegreat** [comment]
Replace this:
  B00000001,
  B00000100,
  B00001000,
  B00000010};

With this:
  B00001001,
  B00000110,
  B00001001,
  B00000110};

This forces wasted spark to be active all the time. Useful for quickly testing

**Comment by rektbink** [comment]
Does it take longer to start OR does it fail to start sometimes when using this method?

**Comment by dalathegreat** [comment]
It sometimes fails to start because the first spark events cause immediate failure of the sequencing. Be ready on the reset button.

**Comment by dalathegreat** [comment]
Setting this one as resolved

No further observations of sync loss after taking v1.4 into use. Engine ran successfully on road up to 8000rpm. Total runtime was over 45 minutes.

I will keep the other issue case open https://github.com/dalathegreat/Arduino-Coil-On-Plug/issues/6 until someone else has confirmed it working on their setup.
