### ISSUE TITLE
Needs testing with smart coils

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/Arduino-Coil-On-Plug#5]
Application has only been tested with dumb coils;
-Honda CBR600 i4 coils
-AEM 30-2840 4-channel coil driver

This case can be set to resolved once the code has proven successful with smart coils.

**Comment by rektbink** [comment]
VWAG coils tested and working well.

**Comment by dalathegreat** [comment]
Superb, setting this issue to resolved!
